cpm'ed on project

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,8 +1,24 @@
-#!/usr/bin/env bash
-# Only meant to set directory for install
+#!/usr/bin/bash
+export CONFIG_INSTALL_PATH="/usr/local/"
 
-if [[ $1 =~ --prefix=(.+)$ ]];then
-	echo "PREFIX=${BASH_REMATCH[1]}" > Makefile.in;
+for arg in "$@"; do
+	if [[ $arg =~ --prefix=(.+) ]];then
+		CONFIG_INSTALL_PATH="${BASH_REMATCH[1]}"
+	fi
+done
+
+echo '' >> Makefile.in
+if [[ `command -v gcc` ]]; then
+	echo 'gcc found'
+elif [[ `command -v clang` ]]; then
+	echo 'clang found'
 else
-	echo "Provide --prefix=DIRECTORY";
+	echo 'Compatible C compiler not found.'
+	exit 1
 fi
+
+echo '' > Makefile.in
+for x in `env | grep "^CONFIG_"`; do
+	echo "$x" >> Makefile.in
+done
+
